### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by Fustzecutor** [secureworks/dalton#103]
Hello,

For some reason the install is failing. I'm getting the error below and immediately after the setup exists with the error code shown. I'm not behind a proxy, it's inside a VM, with internet connectivity and no proxy. 

ERROR: Service 'controller' failed to build: The command '/bin/sh -c apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get -y install wireshark-common     p7zip-full' returned a non-zero code: 100

Can anyone help, please ?

Thank you

**Comment by counterthreatunit** [comment]
In `Dockerfile-dalton`, edit the first line from:

`FROM python:2.7.14`

to:

`FROM python:2.7.16`

Or pull the latest `Dockerfile-dalton` file from master.

See further discussion at https://github.com/secureworks/dalton/pull/100

**Comment by Fustzecutor** [comment]
Indeed, ask a stupid question, get a fantastically effective answer - thank you!
