### ISSUE TITLE
tls entries in eve.log

### ISSUE THREAD

**Issue by zoomequipd** [secureworks/dalton#113]
Based on the note in the dalton.py, tls logs in the EVE output is disabled regardless of the version of suricata being used. 

Is it possible to only disable this output if the version of suricata being called doesn't support multiple tls loggers?  (Suri 4 and >= 3.1 as per notes)

**Comment by whartond** [comment]
Should be addressed in https://github.com/secureworks/dalton/pull/133.  Thanks!
