### ISSUE TITLE
include raw log files in Job Zipfile

### ISSUE THREAD

**Issue by zoomequipd** [secureworks/dalton#114]
In the Job Zipfile, it would be nice if all of the log files produced, despite them being supported by Dalton would be attached. 

my problem stems from the EVE JSON file as displayed in the browser has a bunch of escaping done to it, i'd rather just download the file as generated by the engine. 

I'm not sure how the results are stored on the controller, but perhaps a "download" button for each file displayed in the job results too.

**Comment by counterthreatunit** [comment]
The job zip file is what is used to run the job; it doesn't change after submission.  The job results (including log files) can already be pulled via the (job) API -- https://github.com/secureworks/dalton#job-api -- if the UI is unsuitable.

Improvement of displaying EVE/JSON data in the UI is being worked on for a future release.
