### ISSUE TITLE
use suricata socket

### ISSUE THREAD

**Issue by zoomequipd** [secureworks/dalton#128]
Problem: Running 1000 pcaps is slow.

Idea: Start Suricata upon the agent receiving it's first job, load the requested ruleset, start listening on a socket, send the pcaps through the socket.  If the second job uses the same ruleset (hash compare?) then use the socket to run the pcap without having to spend the time reloading suri.  If the third job uses a different ruleset, you can either restart suricata, or use the socket ruleset-reload-rules.  

Outcome:  Using the same ruleset consecutively between jobs is significantly faster, while still maintaining the original speed if a different ruleset is desired.

**Comment by counterthreatunit** [comment]
Thanks zoomequipd.  This idea has been kicked around a few times over the years but never implemented.  I think it has merit and I like the ruleset hash method; you'd have to include the config and variables in the hash too.

What's your use case? Just faster times for manually submitted jobs? Or are you programmatically submitting "1000 pcaps" as individual jobs?  If the latter, a related feature could be to have an option in the interface to tell Dalton to treat each pcap as separate job and then you could submit a tgz or zip with multiple pcaps.

**Comment by zoomequipd** [comment]
My use case is programmatically submitting thousands of pcaps - a feature to split out pcaps from a archive file would be awesome. I wonder though how it'd be possible to tie the results back to the original pcap.

**Comment by counterthreatunit** [comment]
This is definately on the to-do list to explore although it doesn't have top priority at the moment.

The immediately available solution for quickly processing thousands of jobs is to spin up dozens, hundreds, or more Dalton Agent containers (and you can use the same image).

**Comment by whartond** [comment]
Implemented, thanks! -- https://github.com/secureworks/dalton/pull/133
