### ISSUE TITLE
dalton_controller constantly restarting

### ISSUE THREAD

**Issue by admln** [secureworks/dalton#146]
![image](https://user-images.githubusercontent.com/6093870/157410724-4fa3bece-834e-4bb1-b1c1-0223611ab04b.png)

**Comment by 0x120102181f0a040a01181c** [comment]
I pulled the repo to a clean machine and built it and also saw the dalton_controller container restarting but with a different error. The [most recent version](https://pypi.org/project/itsdangerous/#history) of the itsdangerous library was the issue. I've added an explicit entry for it in the requirements file. If you build with that fix, are you still receiving an error?

**Comment by admln** [comment]
The version I use is 2.0.1, and the problem of importing json is no longer reported, but "no module name app.dalton" is reported. May I ask what version of itsdangerous are you using?

**Comment by 0x120102181f0a040a01181c** [comment]
It wasn't explicitly specified in the requirements until now but it's 2.0.1 now. That changed fixed my issue of the controller restarting. Are you still having the issue with it not finding app.dalton with this new change? I'm not sure what would be causing that. I'm not having this issue when pulling to a clean machine.

**Comment by admln** [comment]
Okay thank you. 
Will it be related to the version of docker and docker compose? The version I am using is ‘Docker version 1.13.1, build 7d71120/1.13.1’.

**Comment by 0x120102181f0a040a01181c** [comment]
Most likely. That version is a few years old now. Are you able to test on a more recent version?

**Comment by admln** [comment]
It must be my environment.I used a clean environment and the build was successful.Thank you!
