### ISSUE TITLE
dalton controller erroring on jinja import

### ISSUE THREAD

**Issue by sstover-cyberadapt** [secureworks/dalton#149]
I see some other "dalton controller constantly restarting" issues, but none of them seem to relate to my issue.  Clean git pull (I deleted my old dalton install, upgraded Docker, etc) and everything starts but the dalton_controller, which repeats this error:

Traceback (most recent call last):
  File "/opt/dalton/run.py", line 1, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)

From my googling (https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2), it appears that the recommended fix for this is to upgrade to a newer version of Flask, which seems like it's not an option.

Is there something else that I'm missing?  Host system is macOS, Docker version is "Docker version 20.10.14, build a224086".

TIA.

**Comment by 0x120102181f0a040a01181c** [comment]
Thanks for reporting this. Looks like JInja2 had an update recently and the version isn't specified in the requirements file. Could you try adding `Jinja2==3.0.3` to the top of the requirements.txt file and rebuild the controller image? That worked in my test env.
