### ISSUE TITLE
start-dalton.sh Fails to build Suricata 7.x (Dockerfile_suricata needs libpcre2-dev

### ISSUE THREAD

**Issue by da667** [secureworks/dalton#167]
Hello!

I'd like to report a small issue with Dalton. the `dalton-agent/Dockerfiles/Dockerfile_suricata` needs to be updated -- somewhere between lines 10 through 15, would you very kindly add `libpcre2-dev` to the list of installed packages?

The docker image for Suricata "latest" (7.0.0) failed to compile suricata because `libpcre2-dev` was missing in the image. To resolve this issue I just updated the docker file and added `libpcre2-dev` next to `libpcre3`, and re-ran `start-dalton.sh` and everything was right as rain.

Host operating system: Ubuntu 22.04.3
Docker compose version info:
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

Proposed change (PR #168) :

```
RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3.8 \
    tcpdump \
    libpcre2-dev libpcre3 libpcre3-dbg libpcre3-dev libnss3-dev\
    build-essential autoconf automake libtool libpcap-dev libnet1-dev \
    libyaml-0-2 libyaml-dev zlib1g zlib1g-dev libcap-ng-dev libcap-ng0 \
    make libmagic-dev libjansson-dev libjansson4 pkg-config rustc cargo \
    liblua5.1-dev libevent-dev
```

**Comment by rkoumis** [comment]
Thanks @da667 and your PR #168 would have been great. As I mentioned, I merged #171 already.
