### ISSUE TITLE
Please add tcp handshake for tcp/http pcap generation

### ISSUE THREAD

**Issue by kirillwow** [secureworks/dalton#74]
Case when I generate pcap in flowsynth and pass it to the dalton in web interface doesnt work due to tcp handshake absence.
Suricata doesnt work with tcp handshakeless sessions so please add tcp.initialize to 

https://github.com/secureworks/dalton/blob/daea41a3329d82a5af6800b00695e921cf48f46a/app/flowsynth.py#L201
`synth = "flow default %s %s:%s > %s:%s%s (	tcp.initialize; ) ; " % (`

or the case is broken otherwise.

**Comment by counterthreatunit** [comment]
This functionality has always been in the Flowsynth WebUI; see the code immediately before and after the referenced line:

[https://github.com/secureworks/dalton/blob/9decb9064542f899e1208d8d6945ae8bd93759f9/app/flowsynth.py#L196-L202](https://github.com/secureworks/dalton/blob/9decb9064542f899e1208d8d6945ae8bd93759f9/app/flowsynth.py#L196-L202)

In the Flowsynth WebUI, checking the "Flow Established" checkbox on the "Transport Layer" vertical tab will cause " (tcp.initialize;)" to be included in the generated Flowsynth language.  It should be checked by default.
